In [487]:
import numpy as np
import pandas as pd

In [488]:
df = pd.read_csv("C:\\Users\\ABIN ANAND\\Desktop\\Data Science\\Projects\\IRCTC Berth prediction\\irctc_berth_dataset.csv")

In [489]:
df.head()

,age,gender,booking_status,quota,coach_type,booking_time,travel_distance,waiting_list_number,seat_preference,berth_type
0,56,M,RAC,GN,2AC,14,1230,8,SL,SL
1,38,M,CNF,GN,2AC,18,1338,0,LB,LB
2,28,M,CNF,LD,3AC,20,1223,0,LB,LB
3,57,M,RAC,GN,SL,21,1432,2,UB,SL
4,41,M,RAC,LD,2AC,5,485,1,NaN,SL

In [490]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  12000 non-null  int64
 1   gender               12000 non-null  object
 2   booking_status       12000 non-null  object
 3   quota                12000 non-null  object
 4   coach_type           12000 non-null  object
 5   booking_time         12000 non-null  int64
 6   travel_distance      12000 non-null  int64
 7   waiting_list_number  12000 non-null  int64
 8   seat_preference      8966 non-null   object
 9   berth_type           12000 non-null  object
dtypes: int64(4), object(6)
memory usage: 937.6+ KB

In [491]:
df.describe()

                age  booking_time  travel_distance  waiting_list_number
count  12000.000000  12000.000000     12000.000000         12000.000000
mean      43.458417     11.511250      1051.363333             4.045333
std       14.903941      6.888734       546.348338             6.052231
min       18.000000      0.000000       100.000000             0.000000
25%       31.000000      6.000000       588.000000             0.000000
50%       43.000000     12.000000      1045.500000             0.000000
75%       56.000000     17.000000      1526.000000             8.000000
max       69.000000     23.000000      1999.000000            19.000000

In [492]:
df.isnull().sum()

age                       0
gender                    0
booking_status            0
quota                     0
coach_type                0
booking_time              0
travel_distance           0
waiting_list_number       0
seat_preference        3034
berth_type                0
dtype: int64

In [493]:
df["seat_pref_missing"] = df["seat_preference"].isnull().astype(int)
df["seat_preference"].fillna("Unknown", inplace=True)

In [494]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  12000 non-null  int64
 1   gender               12000 non-null  object
 2   booking_status       12000 non-null  object
 3   quota                12000 non-null  object
 4   coach_type           12000 non-null  object
 5   booking_time         12000 non-null  int64
 6   travel_distance      12000 non-null  int64
 7   waiting_list_number  12000 non-null  int64
 8   seat_preference      12000 non-null  object
 9   berth_type           12000 non-null  object
 10  seat_pref_missing    12000 non-null  int64
dtypes: int64(5), object(6)
memory usage: 1.0+ MB

In [495]:
df.isnull().sum()

age                    0
gender                 0
booking_status         0
quota                  0
coach_type             0
booking_time           0
travel_distance        0
waiting_list_number    0
seat_preference        0
berth_type             0
seat_pref_missing      0
dtype: int64

In [496]:
df["seat_preference"].value_counts()

seat_preference
Unknown    3034
LB         2995
SL         2989
UB         2982
Name: count, dtype: int64

In [497]:
df.columns

Index(['age', 'gender', 'booking_status', 'quota', 'coach_type',
       'booking_time', 'travel_distance', 'waiting_list_number',
       'seat_preference', 'berth_type', 'seat_pref_missing'],
      dtype='object')

In [498]:
df["berth_type"].value_counts()

berth_type
LB    3740
SL    3628
SU    2357
UB    1168
MB    1107
Name: count, dtype: int64

In [499]:
from sklearn.preprocessing import LabelEncoder

le_dict = {}
for col in df.columns:
    if df[col].dtype == "object":
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])
        le_dict[col] = le

In [500]:
X = df.drop("berth_type",axis=1)
Y = df["berth_type"]

In [501]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [502]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [503]:
from imblearn.over_sampling import SMOTE

sm = SMOTE()
X_train, Y_train = sm.fit_resample(X_train, Y_train)

In [504]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import  accuracy_score,f1_score
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier

In [505]:
models = [DecisionTreeClassifier,KNeighborsClassifier,GaussianNB,XGBClassifier,RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier]

for model in models:
    md = model()
    md.fit(X_train,Y_train)
    y_predict = md.predict(X_test)
    print("===========",model,"===========")
    print("Accuracy score : ",accuracy_score(Y_test,y_predict)*100)
    print("F1 score = ",f1_score(Y_test,y_predict,average="weighted")*100)

=========== <class 'sklearn.tree._classes.DecisionTreeClassifier'> ===========
Accuracy score :  70.20833333333333
F1 score =  70.22703201200959
=========== <class 'sklearn.neighbors._classification.KNeighborsClassifier'> ===========
Accuracy score :  65.875
F1 score =  64.93852123609489
=========== <class 'sklearn.naive_bayes.GaussianNB'> ===========
Accuracy score :  61.541666666666664
F1 score =  57.36346787080397
=========== <class 'xgboost.sklearn.XGBClassifier'> ===========
Accuracy score :  70.125
F1 score =  69.99887733618017
=========== <class 'sklearn.ensemble._forest.RandomForestClassifier'> ===========
Accuracy score :  69.25
F1 score =  68.6479245205096
=========== <class 'sklearn.ensemble._weight_boosting.AdaBoostClassifier'> ===========
Accuracy score :  48.45833333333333
F1 score =  45.62141857504085
=========== <class 'sklearn.ensemble._gb.GradientBoostingClassifier'> ===========
Accuracy score :  70.25
F1 score =  67.61900143086918

In [506]:
import joblib

joblib.dump(md, "model.pkl")
joblib.dump(le_dict, "encoders.pkl")

['encoders.pkl']